name: CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-test-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci
        # Si no usas package-lock.json, cambia por: npm install

      - name: Run tests
        run: npm test

      - name: Set image tags
        id: meta
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/hola-mundo-web
          SHA_TAG=${GITHUB_SHA::7}
          echo "image=${IMAGE}" >> $GITHUB_OUTPUT
          echo "tags=${IMAGE}:latest,${IMAGE}:${SHA_TAG}" >> $GITHUB_OUTPUT

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Deploy to Render
        if: github.ref == 'refs/heads/main'
        run: curl -fsSL "${{ secrets.RENDER_DEPLOY_HOOK }}"
